# Port sur lequel l'app va tourner
server.port=8081

# Nom du microservice (utile pour Eureka ou logs)
spring.application.name=auteur-service

# Connexion à la BDD Postgres du container Docker (attention au port !)
spring.datasource.url=jdbc:postgresql://localhost:5433/auteurdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true